services:
  postgres:
    container_name: bms_db
    image: postgres
    hostname: localhost
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bms_db
    volumes:
      - .postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: bms-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    restart: unless-stopped

  spring-boot-app:
    container_name: bank-management
    image: bank-management
    build: .
    ports:
      - "8081:8081"  # Map port 8080 of the container to 8080 on your machine
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bms_db:5432/bms_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
    restart: unless-stopped

